### ISSUE TITLE
Problems for dextract's parameter -e 

### ISSUE THREAD

**Issue by zwm0502** [thegenemyers/DEXTRACTOR#24] opened 2018-03-10 12:59 UTC
dextract -f -e exp\(ln>=100 && rq>=500\) m180308_162212_00000_cclrbam_p6_s1_p0.bax.h5  
dextract: Filter expression syntax error:

    
    ^ Unrecognized token
dextract: Cannot find ./exp(ln with a Pacbio extension

I want to use the parameter -e  ,but it doesn't work. Could you please tell me what's the problem  ?
Thank you very much!

**Comment by thegenemyers** [comment] 2018-03-11 19:21
You need to escape the expression from the Unix shell with single 
quotes.  The > is being interpreted
as redirection of the standard output by the Unix shell.
    -- Gene

**Comment by thegenemyers** [comment] 2018-05-13 12:41
Actually, I was about to close this and took another look at your expression.
The problem is the space between the -e and the expression, there should be
none.

**Closed by thegenemyers** 2018-05-13 12:41 UTC
